### PR TITLE
Added compatibility with Redis ACL, using AUTH command with username and passsword.

### PR DESCRIPTION
**Pull request by gdub**
## What do these changes do?

* Added support for Redis ACL, by adding optional username parameter throughout the various connection classes.
* `RedisConnection.auth` method updated to accept username and password.
* With this patch, I'm able to successfully use Redis ACL username+password via `aioredis.create_sentinel()`.
* URI-based parsing/connection (with username) has not been tested.

## Are there changes in behavior for the user?

* `RedisConnection.auth()` parameters updated to take both username and password, rather than just password. If username given, then an AUTH command is issued with username and password; otherwise, an AUTH command is issued with just password. Not sure if this lower level API is meant to be used by user code, but if so then this is backwards incompatible.

## Related issue number

#818

## Checklist

- [ ] I think the code is well written
- [ ] Unit tests for the changes exist
- [ ] Documentation reflects the changes
- [ ] If you provide code modification, please add yourself to `CONTRIBUTORS.txt`
  * The format is `<Name> <Surname>`.
  * Please keep alphabetical order, the file is sorted by names. 
- [ ] Add a new news fragment into the [`CHANGES/`](../tree/master/CHANGES) folder
  * name it `<issue_id>.<type>` (e.g. `588.bugfix`)
  * if you don't have an `issue_id` change it to the pr id after creating the PR
  * ensure type is one of the following:
    * `.feature`: Signifying a new feature.
    * `.bugfix`: Signifying a bug fix.
    * `.doc`: Signifying a documentation improvement.
    * `.removal`: Signifying a deprecation or removal of public API.
    * `.misc`: A ticket has been closed, but it is not of interest to users.
  * Make sure to use full sentences with correct case and punctuation, for example:
   `Fix issue with non-ascii contents in doctest text files.`

### CODE REVIEW

**Comment by seandstewart** [comment]
@gdub -

Thank you for your submission! Would you be willing to resolve your merge conflicts? After which you may be asked to sign a CLA, then we should be good to merge this into the main branch!

**Comment by seandstewart** [comment]
Hey @gdub - just want to check in on the status of the pull request.

**Comment by gdub** [comment]
@seandstewart I'm not seeing any merge conflicts in the diff any longer. That said, there are some outstanding items still needed with this pull request:

- Needs doc updates.
- May need further work on the URL-based config with a username (marked with a TODO in the changes), as I haven't attempted/tested connecting via URI-based config.
- Needs tests. I had taken a quick look at this previously, and found that work will be needed for the testing infrastructure to:
  - Install a Redis instance with ACL support (i.e. version 6+)
  - Enhance the test utilities for starting/configuring test Redis instances so that they can configure username/ACL.

I'm not sure when I'll have time to revisit. If someone would be able to assist with any of these, great. Otherwise, I can pick back up when I find some time.

**Comment by seandstewart** [comment]
Hey @gdub - thanks for the contribution! However, this change has been superseded by #891.

**Pull request closed without merging**
