### PR TITLE
Set single_connection_client for Pipeline

### PR DESCRIPTION
**Pull request by rad-pat**
## What do these changes do?

Fix `AttributeError` when using a pipeline

## Are there changes in behavior for the user?

No

## Related issue number

https://github.com/aio-libs/aioredis-py/issues/1025

## Checklist

- [x] I think the code is well written
- [x] Unit tests for the changes exist
- [ ] Documentation reflects the changes
- [x] If you provide code modification, please add yourself to `CONTRIBUTORS.txt`
  * The format is `<Name> <Surname>`.
  * Please keep alphabetical order, the file is sorted by names.
- [x] Add a new news fragment into the [`CHANGES/`](../tree/master/CHANGES) folder
  * name it `<issue_id>.<type>` (e.g. `588.bugfix`)
  * if you don't have an `issue_id` change it to the pr id after creating the PR
  * ensure type is one of the following:
    * `.feature`: Signifying a new feature.
    * `.bugfix`: Signifying a bug fix.
    * `.doc`: Signifying a documentation improvement.
    * `.removal`: Signifying a deprecation or removal of public API.
    * `.misc`: A ticket has been closed, but it is not of interest to users.
  * Make sure to use full sentences with correct case and punctuation, for example:
   `Fix issue with non-ascii contents in doctest text files.`

### CODE REVIEW

**Review by seandstewart — APPROVED** [review]
Looks good to me! Thanks for the fix.

**Comment by seandstewart** [comment]
@rad-pat could you run `make lint` then push the changes?

**Comment by rad-pat** [comment]
Yep, will do

**Comment by rad-pat** [comment]
https://github.com/aio-libs/aioredis-py/pull/1029 is a better solution to the problem

**Comment by seandstewart** [comment]
Closed in favor of 

> #1029 is a better solution to the problem

Closed in favor of an awaitable Pipeline

**Pull request closed without merging**
