### PR TITLE
Support for async callbacks

### PR DESCRIPTION
**Pull request by stephanm**
## What do these changes do?

As mentioned in #1235 you can't use coroutines as custom callbacks. This patch tries to fix that.
## Are there changes in behavior for the user?

There shouldn't be any changes for the users as sync callbacks are still supported.
## Related issue number

#1235 
## Checklist

- [x] I think the code is well written
- [x] Unit tests for the changes exist
- [ ] Documentation reflects the changes
- [x] If you provide code modification, please add yourself to `CONTRIBUTORS.txt`
  * The format is `<Name> <Surname>`.
  * Please keep alphabetical order, the file is sorted by names.
- [x] Add a new news fragment into the [`CHANGES/`](../tree/master/CHANGES) folder
  * name it `<issue_id>.<type>` (e.g. `588.bugfix`)
  * if you don't have an `issue_id` change it to the pr id after creating the PR
  * ensure type is one of the following:
    * `.feature`: Signifying a new feature.
    * `.bugfix`: Signifying a bug fix.
    * `.doc`: Signifying a documentation improvement.
    * `.removal`: Signifying a deprecation or removal of public API.
    * `.misc`: A ticket has been closed, but it is not of interest to users.
  * Make sure to use full sentences with correct case and punctuation, for example:
   `Fix issue with non-ascii contents in doctest text files.`

### CODE REVIEW

**Review by Andrew-Chen-Wang — CHANGES_REQUESTED** [review]
Can you add a test where you receive two callbacks, one is sync and the other an async func? Thanks a ton! Also, pertaining to ordering, I can't actually remember my digging around of the code. In relation to your comment, dicts should be ordered now in supported Py3 versions, but I suppose it doesn't matter here 😅

**Comment by stephanm** [comment]
Yeah, no problem, I'll add the test and have a look at the linter error.
Thanks for the clarifications and the fast feedback!
TIL: Ordering is guaranteed since 3.7 :)

**Comment by stephanm** [comment]
I added a test case that uses both callback variants.

The typing problem wasn't that easy to fix.
Using something like
`PubSubHandler = Callable[[Dict[str, str]], Union[None, Awaitable[None]]]`
doesn't work:
`aioredis/client.py:4236: error: Incompatible types in "await" (actual type "Optional[Awaitable[None]]", expected type "Awaitable[Any]")  [misc]`
Maybe someone who is better at this typing stuff can comment on this issue? The current variant at least works with mypy :)

**Review by seandstewart — APPROVED** [review]
Thanks for your contribution here!

**Pull request merged**
