### PR TITLE
Fix codecov folder structure

### PR DESCRIPTION
**Pull request by Andrew-Chen-Wang**
Supersedes #956 to resolve the comments about how you couldn't actually view the files...

Final solution comes from: https://github.com/thomasrockhu/aioredis-py/pull/1

### CODE REVIEW

**Comment by Andrew-Chen-Wang** [comment]
nope

**Comment by Andrew-Chen-Wang** [comment]
arg...

**Comment by AraHaan** [comment]
Just so you know there was a security notice on codecov as well. As such I migrated from codecov to codacy, and it integrates well with github actions too.

Despite my project being .NET, it supports python, C, C++, ext. and as such I think it's a better alternative to codecov that is more secured.

This also means all the aio-libs repositories might need to invalidate every authentication token that may have been exposed by the hacked bash runners that would send the things in $env over to their external servers.

**Comment by Andrew-Chen-Wang** [comment]
@AraHaan thanks for the comment. You can suggest codacy over at https://aio-libs.discourse.group/ I'm not head of this repo -- just a broke college student that wants to fix this damn bug... I think the comment about being "more secure" isn't really necessary in the context of open source projects. Hacks happen all the time, and we don't pay money for open source libs so I think we're fine. But thanks for the comment!

**Comment by Andrew-Chen-Wang** [comment]
Solution fixed: https://github.com/thomasrockhu/aioredis-py/pull/1 Thanks to tom on codecov! Forum explanation: https://community.codecov.io/t/cant-view-files-on-codecov/2833/2

**Review by seandstewart — APPROVED** [review]

**Pull request merged**
