### PR TITLE
Fix codecov paths

### PR DESCRIPTION
**Pull request by Andrew-Chen-Wang**
Codecov does not pick up on all files, e.g. aioredis/connection.py located at this commit in codecov: https://codecov.io/gh/aio-libs/aioredis-py/tree/b9694797d452bb8d4ca26d2dc14ce73068575130. Resolve via comment in codecov forum: correct fix: https://community.codecov.io/t/codecov-report-missing-files/1928/9 original fix: ~~https://community.codecov.io/t/missing-files-in-codecov-but-not-in-report/825/9~~

### CODE REVIEW

**Comment by Andrew-Chen-Wang** [comment]
Ok well that didn't work

**Comment by Andrew-Chen-Wang** [comment]
Boom e6d759d got it working

**Review by seandstewart — APPROVED** [review]

**Comment by seandstewart** [comment]
Thanks for this!!

**Comment by Andrew-Chen-Wang** [comment]
Not yet @seandstewart remove the ./ first

**Comment by Andrew-Chen-Wang** [comment]
all squash and merge should make it into one commit instead of 3

**Comment by Andrew-Chen-Wang** [comment]
also let's see if that commit also broke it... hopefully not :)

**Comment by Andrew-Chen-Wang** [comment]
Still missing __init__.py for some reason... though it's just imports so I think we're gtg

**Comment by Andrew-Chen-Wang** [comment]
curiously on master branch I can't view the files no more... it says 404 not found... ffs no wonder the file structure was all in a line. So although the coverage worked, codecov couldn't understand relative urls perhaps?

**Pull request merged**
