### PR TITLE
Use asyncio event loop to get time

### LINKED ISSUE #1003: [2.0] Use loop.time() instead of time.time() for health checks
In the 2.0 alpha, health checks are based around `time.time`. Using `asyncio.get_event_loop().time()` has several advantages:
- The default implementation uses a monotonic clock, so it won't go wonky if the system time is changed.
- It sticks to a consistent source of time relative to things like `async_timeout`, which makes mocking out time easier (e.g. with [async-solipsism](https://github.com/bmerry/async-solipsism)).

I'm happy to submit a PR if there is agreement that this is a reasonable change.

### PR DESCRIPTION
**Pull request by bmerry**
## What do these changes do?

This ensures that all timing uses a consistent (and monotonic) clock. This should probably only get merged if a similar redis-py PR (https://github.com/andymccurdy/redis-py/pull/1491) which switches from time.time to time.monotonic is accepted.

Closes #1003.

## Are there changes in behavior for the user?

No, unless they're mocking time, in which case only one source of time needs mocking (I'm hoping this will work with fakeredis + async-solipsism, but haven't test it yet).

## Related issue number

#1003

## Checklist

- [x] I think the code is well written
- [x] Unit tests for the changes exist
- [ ] Documentation reflects the changes
- [ ] If you provide code modification, please add yourself to `CONTRIBUTORS.txt`
  * The format is `<Name> <Surname>`.
  * Please keep alphabetical order, the file is sorted by names.
- [ ] Add a new news fragment into the [`CHANGES/`](../tree/master/CHANGES) folder
  * name it `<issue_id>.<type>` (e.g. `588.bugfix`)
  * if you don't have an `issue_id` change it to the pr id after creating the PR
  * ensure type is one of the following:
    * `.feature`: Signifying a new feature.
    * `.bugfix`: Signifying a bug fix.
    * `.doc`: Signifying a documentation improvement.
    * `.removal`: Signifying a deprecation or removal of public API.
    * `.misc`: A ticket has been closed, but it is not of interest to users.
  * Make sure to use full sentences with correct case and punctuation, for example:
   `Fix issue with non-ascii contents in doctest text files.`

### CODE REVIEW

**Review by seandstewart — APPROVED** [review]
Hey @bmerry -

I know you have a corresponding PR on redis-py in a similar vein, but IMO, this is enough of an asyncio-specific implementation detail to warrant merging without waiting for the change in redis-py to use `time.monotonic`.

If you want to go ahead and resolve your merge conflict I think we're good to move forward with this one, barring any conflicting opinions from @abrookins or @Andrew-Chen-Wang

**Comment by abrookins** [comment]
> Hey @bmerry -
> 
> I know you have a corresponding PR on redis-py in a similar vein, but IMO, this is enough of an asyncio-specific implementation detail to warrant merging without waiting for the change in redis-py to use `time.monotonic`.
> 
> If you want to go ahead and resolve your merge conflict I think we're good to move forward with this one, barring any conflicting opinions from @abrookins or @Andrew-Chen-Wang

I've been thinking along the same lines, Sean. Let's do it.

Philosophically, I view aioredis-py as a drop-in replacement for redis-py that gets you async features. The API that the user uses should be the same, but we should feel free to make internal changes.

**Comment by bmerry** [comment]
I've resolved the conflict. Thanks for doing the legwork to get a new release.

**Comment by abrookins** [comment]
Thanks yet again, @bmerry!

**Pull request merged**
